scrape_configs:  
    - job_name: 'docker-health'    
      static_configs:      
        - targets: ['docker-health-exporter:9066']        
          labels:          
            instance: 'jalen-linux-mint'  
    - job_name: 'cadvisor'    
      static_configs:      
        - targets: ['cadvisor:8080']
      metric_relabel_configs:
        - source_labels: [container_label_com_docker_compose_service]
          target_label: name
          regex: '(.+)'
          replacement: '$1'

        - source_labels: [container_label_com_docker_compose_container_number]
          target_label: name
          regex: '(.+)'
          replacement: '$1'
